// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/repos/algo/type.go

// Package mock_algo is a generated GoMock package.
package mock_algo

import (
	gomock "github.com/golang/mock/gomock"
)

// MockAlgoRepo is a mock of AlgoRepo interface.
type MockAlgoRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAlgoRepoMockRecorder
}

// MockAlgoRepoMockRecorder is the mock recorder for MockAlgoRepo.
type MockAlgoRepoMockRecorder struct {
	mock *MockAlgoRepo
}

// NewMockAlgoRepo creates a new mock instance.
func NewMockAlgoRepo(ctrl *gomock.Controller) *MockAlgoRepo {
	mock := &MockAlgoRepo{ctrl: ctrl}
	mock.recorder = &MockAlgoRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlgoRepo) EXPECT() *MockAlgoRepoMockRecorder {
	return m.recorder
}
