// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package links

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// LinkServiceClient is the client API for LinkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LinkServiceClient interface {
	Shorten(ctx context.Context, in *ShortenReq, opts ...grpc.CallOption) (*ShortenRes, error)
	GetOriginalFromShorten(ctx context.Context, in *GetOriginalFromShortenReq, opts ...grpc.CallOption) (*GetOriginalFromShortenRes, error)
}

type linkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLinkServiceClient(cc grpc.ClientConnInterface) LinkServiceClient {
	return &linkServiceClient{cc}
}

func (c *linkServiceClient) Shorten(ctx context.Context, in *ShortenReq, opts ...grpc.CallOption) (*ShortenRes, error) {
	out := new(ShortenRes)
	err := c.cc.Invoke(ctx, "/example.LinkService/Shorten", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkServiceClient) GetOriginalFromShorten(ctx context.Context, in *GetOriginalFromShortenReq, opts ...grpc.CallOption) (*GetOriginalFromShortenRes, error) {
	out := new(GetOriginalFromShortenRes)
	err := c.cc.Invoke(ctx, "/example.LinkService/GetOriginalFromShorten", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LinkServiceServer is the server API for LinkService service.
// All implementations should embed UnimplementedLinkServiceServer
// for forward compatibility
type LinkServiceServer interface {
	Shorten(context.Context, *ShortenReq) (*ShortenRes, error)
	GetOriginalFromShorten(context.Context, *GetOriginalFromShortenReq) (*GetOriginalFromShortenRes, error)
}

// UnimplementedLinkServiceServer should be embedded to have forward compatible implementations.
type UnimplementedLinkServiceServer struct {
}

func (UnimplementedLinkServiceServer) Shorten(context.Context, *ShortenReq) (*ShortenRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shorten not implemented")
}
func (UnimplementedLinkServiceServer) GetOriginalFromShorten(context.Context, *GetOriginalFromShortenReq) (*GetOriginalFromShortenRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOriginalFromShorten not implemented")
}

// UnsafeLinkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LinkServiceServer will
// result in compilation errors.
type UnsafeLinkServiceServer interface {
	mustEmbedUnimplementedLinkServiceServer()
}

func RegisterLinkServiceServer(s grpc.ServiceRegistrar, srv LinkServiceServer) {
	s.RegisterService(&_LinkService_serviceDesc, srv)
}

func _LinkService_Shorten_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServiceServer).Shorten(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.LinkService/Shorten",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServiceServer).Shorten(ctx, req.(*ShortenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkService_GetOriginalFromShorten_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOriginalFromShortenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServiceServer).GetOriginalFromShorten(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.LinkService/GetOriginalFromShorten",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServiceServer).GetOriginalFromShorten(ctx, req.(*GetOriginalFromShortenReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _LinkService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.LinkService",
	HandlerType: (*LinkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Shorten",
			Handler:    _LinkService_Shorten_Handler,
		},
		{
			MethodName: "GetOriginalFromShorten",
			Handler:    _LinkService_GetOriginalFromShorten_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "links.proto",
}
