// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.15.2
// source: links/links.proto

package links

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortenLinkReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link string `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
}

func (x *ShortenLinkReq) Reset() {
	*x = ShortenLinkReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_links_links_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenLinkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenLinkReq) ProtoMessage() {}

func (x *ShortenLinkReq) ProtoReflect() protoreflect.Message {
	mi := &file_links_links_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenLinkReq.ProtoReflect.Descriptor instead.
func (*ShortenLinkReq) Descriptor() ([]byte, []int) {
	return file_links_links_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenLinkReq) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type ShortenLinkRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortLink string `protobuf:"bytes,1,opt,name=shortLink,proto3" json:"shortLink,omitempty"`
}

func (x *ShortenLinkRes) Reset() {
	*x = ShortenLinkRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_links_links_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenLinkRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenLinkRes) ProtoMessage() {}

func (x *ShortenLinkRes) ProtoReflect() protoreflect.Message {
	mi := &file_links_links_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenLinkRes.ProtoReflect.Descriptor instead.
func (*ShortenLinkRes) Descriptor() ([]byte, []int) {
	return file_links_links_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenLinkRes) GetShortLink() string {
	if x != nil {
		return x.ShortLink
	}
	return ""
}

type GetLinkReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetLinkReq) Reset() {
	*x = GetLinkReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_links_links_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLinkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkReq) ProtoMessage() {}

func (x *GetLinkReq) ProtoReflect() protoreflect.Message {
	mi := &file_links_links_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkReq.ProtoReflect.Descriptor instead.
func (*GetLinkReq) Descriptor() ([]byte, []int) {
	return file_links_links_proto_rawDescGZIP(), []int{2}
}

func (x *GetLinkReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetLinkRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link string `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
}

func (x *GetLinkRes) Reset() {
	*x = GetLinkRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_links_links_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLinkRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkRes) ProtoMessage() {}

func (x *GetLinkRes) ProtoReflect() protoreflect.Message {
	mi := &file_links_links_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkRes.ProtoReflect.Descriptor instead.
func (*GetLinkRes) Descriptor() ([]byte, []int) {
	return file_links_links_proto_rawDescGZIP(), []int{3}
}

func (x *GetLinkRes) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type VisitByKeyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *VisitByKeyReq) Reset() {
	*x = VisitByKeyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_links_links_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VisitByKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitByKeyReq) ProtoMessage() {}

func (x *VisitByKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_links_links_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitByKeyReq.ProtoReflect.Descriptor instead.
func (*VisitByKeyReq) Descriptor() ([]byte, []int) {
	return file_links_links_proto_rawDescGZIP(), []int{4}
}

func (x *VisitByKeyReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type VisitByKeyRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VisitByKeyRes) Reset() {
	*x = VisitByKeyRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_links_links_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VisitByKeyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitByKeyRes) ProtoMessage() {}

func (x *VisitByKeyRes) ProtoReflect() protoreflect.Message {
	mi := &file_links_links_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitByKeyRes.ProtoReflect.Descriptor instead.
func (*VisitByKeyRes) Descriptor() ([]byte, []int) {
	return file_links_links_proto_rawDescGZIP(), []int{5}
}

var File_links_links_proto protoreflect.FileDescriptor

var file_links_links_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x1a, 0x1c, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x76, 0x32,
	0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x24, 0x0a, 0x0e, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x65, 0x6e, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04,
	0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b,
	0x22, 0x2e, 0x0a, 0x0e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x4c, 0x69, 0x6e, 0x6b, 0x52,
	0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x4c, 0x69, 0x6e, 0x6b,
	0x22, 0x1e, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x22, 0x20, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69,
	0x6e, 0x6b, 0x22, 0x21, 0x0a, 0x0d, 0x56, 0x69, 0x73, 0x69, 0x74, 0x42, 0x79, 0x4b, 0x65, 0x79,
	0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x0f, 0x0a, 0x0d, 0x56, 0x69, 0x73, 0x69, 0x74, 0x42, 0x79,
	0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x32, 0xa8, 0x02, 0x0a, 0x0b, 0x4c, 0x69, 0x6e, 0x6b, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x86, 0x01, 0x0a, 0x0b, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x65, 0x6e, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x17, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x1a,
	0x17, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65,
	0x6e, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x22, 0x45, 0x92, 0x41, 0x2a, 0x0a, 0x05, 0x4c,
	0x69, 0x6e, 0x6b, 0x73, 0x12, 0x0c, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x20, 0x6c, 0x69,
	0x6e, 0x6b, 0x1a, 0x13, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x20, 0x67, 0x69, 0x76, 0x65,
	0x6e, 0x20, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x22, 0x0d, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x3a, 0x01, 0x2a, 0x12,
	0x8f, 0x01, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x13, 0x2e, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71,
	0x1a, 0x13, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69,
	0x6e, 0x6b, 0x52, 0x65, 0x73, 0x22, 0x5a, 0x92, 0x41, 0x3c, 0x0a, 0x05, 0x4c, 0x69, 0x6e, 0x6b,
	0x73, 0x12, 0x11, 0x47, 0x65, 0x74, 0x20, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x20,
	0x6c, 0x69, 0x6e, 0x6b, 0x1a, 0x20, 0x47, 0x65, 0x74, 0x20, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e,
	0x61, 0x6c, 0x20, 0x6c, 0x69, 0x6e, 0x6b, 0x20, 0x62, 0x79, 0x20, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x20, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15, 0x12, 0x13, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x2f, 0x7b, 0x6b, 0x65, 0x79,
	0x7d, 0x42, 0x82, 0x01, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x61, 0x62, 0x64, 0x79, 0x62, 0x61, 0x65, 0x76, 0x61, 0x65, 0x2f, 0x75, 0x72, 0x6c, 0x2d,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x92, 0x41, 0x4e, 0x12, 0x05, 0x32, 0x03, 0x31, 0x2e, 0x30, 0x2a,
	0x01, 0x02, 0x72, 0x42, 0x0a, 0x13, 0x55, 0x72, 0x6c, 0x20, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65,
	0x6e, 0x20, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2b, 0x68, 0x74, 0x74, 0x70, 0x73,
	0x3a, 0x2f, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x62,
	0x64, 0x79, 0x62, 0x61, 0x65, 0x76, 0x61, 0x65, 0x2f, 0x75, 0x72, 0x6c, 0x2d, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_links_links_proto_rawDescOnce sync.Once
	file_links_links_proto_rawDescData = file_links_links_proto_rawDesc
)

func file_links_links_proto_rawDescGZIP() []byte {
	file_links_links_proto_rawDescOnce.Do(func() {
		file_links_links_proto_rawDescData = protoimpl.X.CompressGZIP(file_links_links_proto_rawDescData)
	})
	return file_links_links_proto_rawDescData
}

var file_links_links_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_links_links_proto_goTypes = []interface{}{
	(*ShortenLinkReq)(nil), // 0: example.ShortenLinkReq
	(*ShortenLinkRes)(nil), // 1: example.ShortenLinkRes
	(*GetLinkReq)(nil),     // 2: example.GetLinkReq
	(*GetLinkRes)(nil),     // 3: example.GetLinkRes
	(*VisitByKeyReq)(nil),  // 4: example.VisitByKeyReq
	(*VisitByKeyRes)(nil),  // 5: example.VisitByKeyRes
}
var file_links_links_proto_depIdxs = []int32{
	0, // 0: example.LinkService.ShortenLink:input_type -> example.ShortenLinkReq
	2, // 1: example.LinkService.GetLink:input_type -> example.GetLinkReq
	1, // 2: example.LinkService.ShortenLink:output_type -> example.ShortenLinkRes
	3, // 3: example.LinkService.GetLink:output_type -> example.GetLinkRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_links_links_proto_init() }
func file_links_links_proto_init() {
	if File_links_links_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_links_links_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortenLinkReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_links_links_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortenLinkRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_links_links_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLinkReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_links_links_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLinkRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_links_links_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VisitByKeyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_links_links_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VisitByKeyRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_links_links_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_links_links_proto_goTypes,
		DependencyIndexes: file_links_links_proto_depIdxs,
		MessageInfos:      file_links_links_proto_msgTypes,
	}.Build()
	File_links_links_proto = out.File
	file_links_links_proto_rawDesc = nil
	file_links_links_proto_goTypes = nil
	file_links_links_proto_depIdxs = nil
}
