// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/repos/key/type.go

// Package mock_key is a generated GoMock package.
package mock_key

import (
	gomock "github.com/golang/mock/gomock"
)

// MockKeyRepo is a mock of KeyRepo interface.
type MockKeyRepo struct {
	ctrl     *gomock.Controller
	recorder *MockKeyRepoMockRecorder
}

// MockKeyRepoMockRecorder is the mock recorder for MockKeyRepo.
type MockKeyRepoMockRecorder struct {
	mock *MockKeyRepo
}

// NewMockKeyRepo creates a new mock instance.
func NewMockKeyRepo(ctrl *gomock.Controller) *MockKeyRepo {
	mock := &MockKeyRepo{ctrl: ctrl}
	mock.recorder = &MockKeyRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyRepo) EXPECT() *MockKeyRepoMockRecorder {
	return m.recorder
}
